#!/bin/bash

if [ $# != 11 ]
then
	echo "Usage: "
	echo "./fixSimuData.sh <simulatedTopDirectory> <simulatedSecondaryDirectory> <simulatedReference.fa> <deviation> <resultReference.fa> <output> \"--Inv <firstStartPosition>--start:<>-end:<firstEndPosition> --size <inversionLength>\" <ISPE> <ISSD> <coverage> <readLength>"
fi

echo
echo "simulated data start"
echo
mkdir $1$2
echo "dos2unix /home/gao/hdg/gao/wuzhongjia/code/codeInvSum/fixSimuData.sh" > $1$2readme
echo "bash /home/gao/hdg/gao/wuzhongjia/code/codeInvSum/fixSimuData.sh $1 $2 $3 $4 $5 $6 \"$7\" $8 $9 ${10} ${11}" >> $1$2readme
echo "simulateSeq.pl --outdir $1$2 $1$3 --div $4 --Seq $1$2$5 --name $6 $7 --ISPE $8 --ISSD $9 --PE ${10} --RL ${11}-${11} --type stdfq > $1$2$6.vcf"
simulateSeq.pl --outdir $1$2 $1$3 --div $4 --Seq $1$2$5 --name $6 $7 --ISPE $8 --ISSD $9 --PE ${10} --RL ${11}-${11} --type stdfq > $1$2$6.vcf
echo
bwa aln -t 8 $1$3 $1$2$6_PE1.fq > $1$2$6_PE1.fq.sai
bwa aln -t 8 $1$3 $1$2$6_PE2.fq > $1$2$6_PE2.fq.sai
bwa sampe $1$3 $1$2$6_PE1.fq.sai $1$2$6_PE2.fq.sai $1$2$6_PE1.fq $1$2$6_PE2.fq > $1$2$6.sam
samtools view -@ 8 -bS $1$2$6.sam > $1$2$6.unsort.bam
samtools sort -@ 8 $1$2$6.unsort.bam > $1$2$6.bam
rm $1$2$6.unsort.bam
samtools index $1$2$6.bam
echo "get simulated bam end"

echo "fixSimuData end"
